POST http://localhost:3000/groups
Content-Type: application/json

{
  "name": "string",
  "description": "string",
  "photoUrl": "string",
  "goalRep": 0,
  "discordWebhookUrl": "string",
  "discordInviteUrl": "string",
  "ownerNickname": "abc",
  "ownerPassword": "123123",
  "tags" : ["string"]
}

###

GET http://localhost:3000/groups/list
Content-Type: application/json

###

GET http://localhost:3000/groups/10


###

PATCH  http://localhost:3000/groups/change/10
Content-Type: application/json

{
  "name": "a수정하자자sd",
  "description": "stㅇㄴㄴring",
  "photoUrl": "strㄴㅇㄴㅇㅇing",
  "goalRep": 0,
  "discordWebhookUrl": "string",
  "discordInviteUrl": "striㄴㅇㄴㄴng",
  "tags" : ["string"],
  "ownerPassword" : "123123"
}