### Record 생성 (POST)
POST http://localhost:3000/groups/1/participants/2/records
Content-Type: application/json

{
  "exerciseType": "running",
  "description": "추가 ",
  "time": 3500,
  "distance": 12500,
  "photos": ["https://example.com/pic.jpg"]
}

### 1) 그룹 내 모든 Record 조회 (GET)
GET http://localhost:3000/groups/2/records?page=1&limit=10

### 2) 특정 참여자의 Record 조회 (GET)
GET http://localhost:3000/groups/2/participants/1/records

### 3) 단일 Record 조회 (GET)
GET http://localhost:3000/groups/1/participants/1/records/1

### 4) Record 삭제 (DELETE)
DELETE http://localhost:3000/groups/1/participants/1/records/1
